version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: orders_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gerry123
      POSTGRES_DB: DataBase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: orders_rabbitmq
    ports:
      - "5672:5672"     # conexión desde backend
      - "15672:15672"   # panel de gestión web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
